// Prints SQL that loads today's site copy into Supabase: npx tsx scripts/seed-sql.ts > supabase/seed.sql
// Existing rows are left alone, so it's safe to run again.
import { sectionDefaults, sectionSchemas, SECTION_KEYS } from '../lib/content/sections'
import { seoDefaults } from '../lib/content/seo'

const q = (s: string) => `'${s.replace(/'/g, "''")}'`
const lines = ['-- Generated by scripts/seed-sql.ts from lib/content defaults.']
for (const key of SECTION_KEYS) {
  const content = sectionSchemas[key].parse(sectionDefaults[key])
  lines.push(`insert into public.jada_sections (key, content) values (${q(key)}, ${q(JSON.stringify(content))}::jsonb) on conflict (key) do nothing;`)
}
for (const [path, s] of Object.entries(seoDefaults)) {
  lines.push(`insert into public.jada_page_seo (path, title, description, og_image) values (${q(path)}, ${q(s.title)}, ${q(s.description)}, ${s.ogImage ? q(s.ogImage) : 'null'}) on conflict (path) do nothing;`)
}
console.log(lines.join('\n'))
